# Generated by Django 3.2.6 on 2021-08-27 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_remove_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
