# Generated by Django 3.2.6 on 2021-08-27 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0009_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Category2',
        ),
    ]
