# Generated by Django 3.2.6 on 2021-08-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0002_alter_post_bnch2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='bnch2',
            new_name='category',
        ),
    ]
