# Generated by Django 3.2.6 on 2021-08-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0003_rename_bnch2_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category2',
            field=models.CharField(default='codex', max_length=255),
        ),
    ]
