# Generated by Django 3.2.6 on 2021-09-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='default snippet', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='category2',
            field=models.CharField(default='code', max_length=255),
        ),
    ]
