# Generated by Django 3.2.6 on 2021-09-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0011_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_Id',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
