# Generated by Django 3.2.6 on 2021-09-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0012_comment_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_Id',
            new_name='IdOfPost',
        ),
    ]
