# Generated by Django 3.2.6 on 2021-09-21 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='IdOfPost',
        ),
    ]
