# Generated by Django 3.2.6 on 2021-09-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0002_remove_comment_idofpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='return_id',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
