# Generated by Django 3.2.6 on 2021-08-27 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
