# Generated by Django 3.2.6 on 2021-08-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0012_auto_20210827_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='code', max_length=255),
        ),
    ]
